### ISSUE TITLE
Bug: Associated functions for click event of the Button component do not work [Part 1c]

### ISSUE THREAD

**Issue by jpsalo** [fullstack-hy2019/fullstack-hy2019.github.io#17]
See the last code snippet in
- https://github.com/fullstack-hy2019/fullstack-hy2019.github.io/blob/source/src/content/osa1/osa1c.md#tilan-vieminen-alikomponenttiin
- https://fullstack-hy2019.github.io/osa1/komponentin_tila_ja_tapahtumankasittely#tilan-vieminen-alikomponenttiin

Most likely they should be changed from
```
handleClick={() => setToValue(counter + 1)}
handleClick={() => setToValue(0)}
```
to
```
handleClick={setToValue(counter + 1)}
handleClick={setToValue(0)}
```

**Comment by JuhQ** [comment]
`handleClick={setToValue(counter + 1)}` will execute `setToValue(counter + 1)` function call immediately and is not the desired functionality here.
You want to pass a function to `handleClick` which will be executed once `onClick` happens.
