### ISSUE TITLE
Part 3 instructions a little unclear

### ISSUE THREAD

**Issue by lappalj4** [fullstack-hy2019/fullstack-hy2019.github.io#36]
So in part 3, when building the backend for the phone number app, the instructions (3.1) tell us to have the api serve a hardcoded list of names and phone numbers. It would make sense that this hardcoded list is not meant to be modified despite the tasks in 3.4 and 3.5 are to implement `DELETE ` and `POST` endpoints respectively. 

This is all fine and well, but the bigger confusion comes in the next chapter when in task 3.9  we are told to make the backend work together with the frontend. How is this supposed to be possible when `POST` requests don't actually add anything to the data on the server and `DELETE` requests don't remove anything?

Perhaps I missed something in the instructions, but could you clarify how exactly this is supposed to be done (prior to implementing any database integration)? Thanks.

**Comment by mluukkai** [comment]
Hardcoding the list means that the state of server returns always to that of the hardcoded list always when the server is started. After start the POST:s and DELETE:s modify the list that serves keeps in the variable.
