### ISSUE TITLE
Possibly old class based code in part 6

### ISSUE THREAD

**Issue by Peanhua** [fullstack-hy2019/fullstack-hy2019.github.io#70]
In part 6, exercise 6.9, there is the following text which looks suspiciously like old class based code:
```
Sovelluksessa on valmiina komponentin Notification runko:
class Notification extends React.Component {
  render() {
```

Also later there is this:
```
class NewNote extends React.Component {
```

**Comment by marklaatikainen** [comment]
Not an issue. Content fixes should be proposed by pull requests.
